### ISSUE TITLE
Cho & Gall Hero Matchups Fail with 500 Server Error

### ISSUE THREAD

**Issue by jpmarcotte** [Zemill/heroesprofile-api-public#38]
This endpoint (token removed) returns a 500 Server Error (Same for hero=Gall): https://api.heroesprofile.com/api/Heroes/Matchups?api_token=REDACTED&mode=json&timeframe_type=major&timeframe=2.49&game_type=Storm%20League&group_by_map=false&hero=Cho

**Comment by Zemill** [comment]
I have fixed this and reset your calls.  I would suggest re-running all of the data as the issue may affect other heroes valid data.

Also,
I have altered the win_rate_as_ally and win_rate_against return to be the full percentage instead of decimal to be consistent with other endpoint percentage returns.  Make sure to account for that.
