### ISSUE TITLE
Hero Talent Builds Endpoint Games Played

### ISSUE THREAD

**Issue by jared-craig** [Zemill/heroesprofile-api-public#45]
Can we get a games_played property on the Heroes/Talents/Builds endpoint? It would be nice to see the most played talent builds.

**Comment by Zemill** [comment]
I have added 3 new items returned

- calculated_wins
- calculated_losses
- calculated_games_played

I am using calculated here because I want to to be obvious that builds are calculated, not "REAL" data.  We make assumptions based on some data to come up with wins, losses, games played, and win rate.  

I have also updated the logic to be inline with the production site.  There was a small discrepancy in how a builds wins, losses, games played, and win rate, were being calculated that had the builds being given slightly more positive values.

**Comment by jared-craig** [comment]
Thank you!

**Comment by jared-craig** [comment]
Just wondering why some builds come back with the same stats even though they usually have 1 different talent choice. Obviously, I'm not sure of the logic going on here as these are "calculated". Still appreciate the effort put in to this endpoint. For example, Li-Ming has 3 talent builds with the same stats, but each has a different level 20 talent.
